# Parameters for the robot description
# Unit for gazebo = meters

wheel_radius: 0.045 # mit gummi
wheel_width: 0.0132
wheel_mounting_offset_z: 0.0116 # von der Unterseite bis zur Radmitte
wheel_mounting_offset_x: 0.048 # von der Mitte des Chassis bis zur Radmitte 
wheel_clearance: 0.0234

chassis_length: 0.168
chassis_width: 0.120
chassis_height: 0.1224
