<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

    <!-- Create base_link and base_footprint -->
    <link name="base_footprint">
    </link>

    <link name="base_link">
    </link>

    <!-- Connect base_link and base_footprint -->
    <joint name="base_link_to_base_footprint" type="fixed" >
        <origin xyz="0 0 ${chassis_height / 2 + wheel_clearance}" rpy="0 0 0" />
        <parent link="base_footprint"/>
        <child link="base_link" />
    </joint>

    <!-- Create chassis link -->
    <link name="chassis">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <mesh filename="file://$(find awdbot_description)/meshes/body.dae" scale="0.001 0.001 0.001" />
            </geometry>
        </visual>
        <collision>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size="${chassis_length} ${chassis_width} ${chassis_height}" />
            </geometry>
        </collision>
        <inertial>
            <mass value="30.0" />
            <origin xyz="0 0 0" />
            <xacro:box_inertia m="30.0" x="${chassis_length}" y="${chassis_width}" z="${chassis_height}" />
        </inertial>
    </link>

    <!-- Connect chassis with base_link -->
    <joint name="base_link_to_chassis" type="fixed" >
        <origin xyz="0 0 0" rpy="0 0 0" />
        <parent link="base_link"/>
        <child link="chassis" />
    </joint>

</robot>