<?xml version="1.0"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
    
    <xacro:include filename="macros/wheels.xacro"/>
    
    <xacro:wheel 
        name="wheel_front_left" 
        parent="base_link" 
        xyz="${wheel_mounting_offset_x} ${chassis_width / 2.0} ${-chassis_height / 2 + wheel_mounting_offset_z}" 
        rpy="0 0 0"
        visual_rpy="0 0 ${MATH_PI}"
        wheel_radius="${wheel_radius}"
        wheel_width="${wheel_width}"
    />

    <xacro:wheel 
        name="wheel_front_right"
        parent="base_link" 
        xyz="${wheel_mounting_offset_x} ${-chassis_width / 2.0} ${-chassis_height / 2 + wheel_mounting_offset_z}" 
        rpy="0 0 0"
        visual_rpy="0 0 0"
        wheel_radius="${wheel_radius}"
        wheel_width="${wheel_width}"
    />

    <xacro:wheel
        name="wheel_rear_left" 
        parent="base_link" 
        xyz="${-wheel_mounting_offset_x} ${chassis_width / 2.0} ${-chassis_height / 2 + wheel_mounting_offset_z}" 
        rpy="0 0 0"
        visual_rpy="0 0 ${MATH_PI}"
        wheel_radius="${wheel_radius}"
        wheel_width="${wheel_width}"
    />

    <xacro:wheel 
        name="wheel_rear_right"
        parent="base_link" 
        xyz="${-wheel_mounting_offset_x} ${-chassis_width / 2.0} ${-chassis_height / 2 + wheel_mounting_offset_z}"
        rpy="0 0 0"
        visual_rpy="0 0 0"
        wheel_radius="${wheel_radius}"
        wheel_width="${wheel_width}"
    />

</robot>