<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:macro name="camera" params="name parent xyz rpy chassis_height">

        <!-- Parse the parameters from the loaded configuration-array -->
        <xacro:property name="camera_height" value="0.006"/>
        <xacro:property name="camera_diameter" value="0.004"/>

        <xacro:property name="camera_link" value="${name}_link"/>
        <xacro:property name="camera_name" value="${name}"/>
        <xacro:property name="camera_topic" value="/${name}/image_raw"/>
        <xacro:property name="update_rate" value="10.0"/> <!--[Hz]-->
        <xacro:property name="visualize" value="1"/>
        <xacro:property name="horizontal_fov" value="1.21126"/>
        <xacro:property name="image_width" value="640"/>
        <xacro:property name="image_height" value="480"/>
        <xacro:property name="image_format" value="RGB_INT8"/>
        <xacro:property name="clip_near" value="0.1"/>
        <xacro:property name="clip_far" value="100"/>
        <xacro:property name="noise_stddev" value="0.007"/>

        <!-- Add camera_mount -->
        <link name="${name}_mount_link">
            <visual>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <cylinder length="${camera_height}" radius="${camera_diameter / 2.0}"/>
                </geometry>
                <material name="green"/>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="0 0 0" />
                <geometry>
                    <cylinder length="${camera_height}" radius="${camera_diameter / 2.0}"/>
                </geometry>
            </collision>
            <inertial>
                <mass value="0.01" />
                <origin xyz="0 0 0" rpy="0 0 0" />
                <xacro:cylinder_inertia m="0.01" r="${camera_diameter / 2.0}" h="${camera_height}" />
            </inertial>
        </link>

        <joint name="${name}_mount_link_joint" type="fixed" >
            <origin xyz="${xyz}" rpy="${rpy}" />
            <parent link="base_link"/>
            <child link="${name}_mount_link" />
        </joint>

        <!-- Add name -->
        <link name="${name}">
        </link>

        <joint name="${name}_joint" type="fixed" >
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <parent link="${name}_mount_link"/>
            <child link="${name}" />
        </joint>

        <gazebo reference="${name}">
            <sensor name="${camera_name}" type="camera">
                <pose relative_to='${name}'>0 0 0 0 0 0</pose>
                <always_on>1</always_on>
                <update_rate>${update_rate}</update_rate>
                <visualize>${visualize}</visualize>
                <pose>0 0 0 0 0 0</pose>
                <topic>${camera_topic}</topic>
                <camera name="${camera_name}">
                    <horizontal_fov>${horizontal_fov}</horizontal_fov>
                    <image>
                        <width>${image_width}</width>
                        <height>${image_height}</height>
                        <format>${image_format}</format>
                    </image>
                    <clip>
                        <near>${clip_near}</near>
                        <far>${clip_far}</far>
                    </clip>
                    <noise>
                        <type>gaussian</type>
                        <mean>0</mean>
                        <stddev>${noise_stddev}</stddev>
                    </noise>
                </camera>
            </sensor>
        </gazebo>
    </xacro:macro>
</robot>